version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: kpa_user
      POSTGRES_PASSWORD: kpa_pass
      POSTGRES_DB: kpa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    environment:
      POSTGRES_HOST: postgres
volumes:
  pgdata:
