name: kpa_frontend
description: Minimal Flutter app for KPA Backend Assignment
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2

flutter:
  uses-material-design: true
